import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import Body from "@/components/body";

const poppins = Poppins({
  weight: ["300", "400", "500", "600", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className="bg-custom-header bg-cover bg-center h-[726px] w-full bg-no-repeat"
    >
      <body className={poppins.className}>
        <Header />

        <Body />
        {children}
      </body>
    </html>
  );
}
